# Generated by Django 2.0.3 on 2018-05-26 00:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('Catagories', models.CharField(max_length=100)),
                ('Date_Needed', models.DateTimeField(verbose_name='Date Needed')),
            ],
        ),
        migrations.RenameField(
            model_name='option',
            old_name='otext',
            new_name='Option_Text',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='ovalue',
            new_name='Option_Value',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='question',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='qtext',
            new_name='Question_Text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='qweight',
            new_name='Question_Weight',
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='question',
            name='Survey',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='surveys.survey'),
            preserve_default=False,
        ),
    ]
